name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=5.7
            DATABASE_CHARSET: utf8mb4
            DATABASE_COLLATE: utf8mb4_unicode_ci

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.3'
                      dependency-versions: 'lowest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled

                    - php-version: '7.4'
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.0'
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

                    - php-version: '8.1'
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: 'imagick'
                  tools: 'composer:v2'

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{matrix.dependency-versions}}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment
              env: ${{ matrix.env }}

            - name: Execute test cases
              run: time composer test
              env: ${{ matrix.env }}

    lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: 'imagick'
                  tools: 'composer:v2'

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{matrix.dependency-versions}}

            - name: Lint code
              run: composer lint
