name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
    workflow_dispatch:

env:
    CI_GROUP_OUTPUT: true

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: "PHP ${{ matrix.php-version }} (${{ matrix.database }}, ${{ matrix.dependency-versions }})"
        runs-on: ubuntu-latest
        timeout-minutes: 30

        env:
            DATABASE_CHARSET: utf8mb4
            DATABASE_COLLATE: utf8mb4_unicode_ci

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.2'
                      dependency-versions: 'lowest'
                      database: mysql-57
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: disabled
                          DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=5.7

                    - php-version: '8.2'
                      dependency-versions: 'highest'
                      database: mysql-80
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=8.0


                    - php-version: '8.3'
                      database: mysql-80
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=8.0

                    - php-version: '8.4'
                      database: mysql-84
                      dependency-versions: 'highest'
                      env:
                          SYMFONY_DEPRECATIONS_HELPER: weak
                          DATABASE_URL: mysql://root:root@127.0.0.1:3306/su_theme_test?serverVersion=8.4

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Start Database
              run: |
                  docker compose -f Tests/docker/docker-compose.${{ matrix.database }}.yml up --wait

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'

            - name: Remove Lint Tools
              # These tools are not required to run tests, so we are removing them to improve dependency resolving and
              # testing lowest versions.
              run: composer remove "*php-cs-fixer*" "*phpstan*" "*rector*" --dev --no-update

            - name: Install composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{matrix.dependency-versions}}
                  composer-options: ${{ matrix.composer-options }}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment
              env: ${{ matrix.env }}

            - name: Execute test cases
              run: time composer test
              env: ${{ matrix.env }}

    lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: 'composer:v2'

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Lint code
              run: composer lint
